import fs from "node:fs/promises";

// Minimal fetch helpers. Errors are loud and carry the response body — BytePlus error
// payloads name the exact problem (moderation codes, quota, bad model ID) and the user
// needs that text verbatim. No retries in v1: generation calls bill real money, and a
// blind retry on an ambiguous failure could double-spend; the agent/user retries deliberately.

export async function postJson(url, headers, body) {
  const res = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json", ...headers },
    body: JSON.stringify(body),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`POST ${url} → HTTP ${res.status}: ${truncate(text)}`);
  return parseJson(text, url);
}

export async function getJson(url, headers) {
  const res = await fetch(url, { headers });
  const text = await res.text();
  if (!res.ok) throw new Error(`GET ${url} → HTTP ${res.status}: ${truncate(text)}`);
  return parseJson(text, url);
}

// Streaming POST: yields the raw response body chunks (Uint8Array). Caller owns framing.
export async function postStream(url, headers, body) {
  const res = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json", ...headers },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`POST ${url} → HTTP ${res.status}: ${truncate(text)}`);
  }
  return res.body;
}

// Generated BytePlus URLs expire in ~24h and tasks are cleared server-side — download
// immediately on success; a bare URL is never an acceptable result.
export async function downloadTo(url, destPath) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`download ${url} → HTTP ${res.status}`);
  const bytes = Buffer.from(await res.arrayBuffer());
  await fs.writeFile(destPath, bytes);
  return { path: destPath, bytes: bytes.length };
}

function parseJson(text, url) {
  try {
    return JSON.parse(text);
  } catch {
    throw new Error(`Non-JSON response from ${url}: ${truncate(text)}`);
  }
}

function truncate(text) {
  const t = text.trim();
  return t.length > 600 ? `${t.slice(0, 600)}…` : t;
}
